language: node_js
node_js:
- '10'
- '8'
- '6'
deploy:
  api_key:
    secure: 2q0X/+3dGp54JJJcCAI9LATr9XX2PfJMgK3qVamF2P1gJnMvnMyzdxEa9VneF+mhkWNv9qnWIa9QVR4NAXLZK8pBpuSXyDH4PpJh7MB8JfsbhkHtQGqE1SkfSU1iLK2yrqKUv5wFK+qXvyq6ceDW8fEArBixJg8IZxFjovw3gnfI9aLj26kirZeP2NxFXVmwg+tELVLIqIGkrRF8bo023ztMJJ7ms4PvXAbEjOoQ+EyNkAJv35AQzSEAPlayuqtZJ1lEWAV8XeZbkKZiIvmH37U8nL4GiPCs3xCn5V+1bYy9skA5jXk5XHrqoS0KlpgatQrJDB7O2dxM+MHSweUeDQmyLML/G6qJTj6iR8RXcdNUyN15fdkM2VOxrkXk4nknXS4Hk/VoPBxEuZHGaSI9dAcEYuzNpejkLOVUfe8hT/M2m7IZE85zH2E2XztSZQD+rqaU18PDJ7L3j6blz5Xi2WxaKdKJD4DjCJYjz1+LMGgw3Pz75BwsTv7SX+16rot3SgEz71phGtj414qT4OzT3tR3CtS3ubwpkyi8RILf3irN22JsFgzn4X/VeGR1fwBf8jiBriyFQZZxSCVNJ8a/rMJcBiGzkSkIYaR0b3TSiciCAT76qRSxPXiGOZkYWHHEUxDpPzR7UOa0a00+4xkmI37QYg4d15mHibsm5Fsx6Mk=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true
  on:
    tags: true
script:
- npm test
after_success:
- npm run coveralls
